version: "2"
services:
  hm-node-stag: 
    image: hm:0.0.1
    container_name: hm-node-stag
    restart: always
    build: .
    ports: 
      - "5002:5002"
    depends_on:
      - hm-database-staging
    environment:
      - DB_HOST=hm-database-staging
      - DB_PORT=27017
      - DB_NAME=helen_staging
      - DB_PROTOCOL=mongodb
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5002
      - DOMAIN_PROTOCOL=http
      - DOMAIN_HOST=127.0.0.1
      - DOMAIN_PORT=5002
      - NODE_ENV=development
      - PLATFORM=hm
  hm-database-staging:
    container_name: hm-database-staging
    image: mongo:4.0
    restart: always
    volumes:
      - ./db-data:/data/db
    ports:
      - "27019:27017"
